### ISSUE TITLE
[Error] Command How To Use

### ISSUE THREAD

**Issue by januridp** [django-id/website#6]
maaf nih om, ane awam dan baru di python, ane mau coba install website django-id di lokal
OS Windows 10 Education 64bit dengan command line bash linux (bukan command prompt)

2 step ini belum berhasil:

# Install requirements
$ pip install -r requirements.txt

yang install requirement ada tulisan merah begini:
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/Pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Razp8z-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/Pillow
Storing debug log for failure in /root/.pip/pip.log

# Migrate the databse
$ python manage.py makemigrations && python manage.py migrate

yang migrate database ada tulisan putih begini:
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 13, in <module>
    from django.core.management.base import (
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 17, in <module>
    from django.db.migrations.exceptions import MigrationSchemaMissing
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/__init__.py", line 2, in <module>
    from .operations import *  # NOQA
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/operations/__init__.py", line 1, in <module>
    from .fields import AddField, AlterField, RemoveField, RenameField
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/operations/fields.py", line 4, in <module>
    from django.db.models.fields import NOT_PROVIDED
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/__init__.py", line 3, in <module>
    from django.db.models.aggregates import *  # NOQA
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/aggregates.py", line 5, in <module>
    from django.db.models.expressions import Func, Star
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/expressions.py", line 5, in <module>
    from django.db.backends import utils as backend_utils
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 12, in <module>
    from django.utils.timezone import utc
  File "/usr/local/lib/python2.7/dist-packages/django/utils/timezone.py", line 8, in <module>
    import pytz
ImportError: No module named pytz

thanks

**Comment by alzearafat** [comment]
Halo mas @januridp 

Thanks report nya. Windows ya? Waduh, ga ada mesin Windows buat debug nya 😕  . Coba barangkali ada yg pakai Windows juga.

Coba install Pillow nya terpisah : `pip install pillow`
 
Asumsi nya ini di dalam virtualenv yak mas.

**Comment by januridp** [comment]
kalo didalam virtualenv berarti harus diaktifin dulu kan virtualenv nya?
mungkin bisa di share pake python versi berapa, pillow versi berapa

update:
berhasil install pillow tapi install ini dulu untuk ubuntu 14.04
`sudo apt-get install libtiff5-dev libjpeg8-dev zlib1g-dev libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev python-tk` [sumber](https://askubuntu.com/questions/547656/install-pillow-on-ubuntu-14-04)

lalu kalo perintah ini `python manage.py makemigrations && python manage.py migrate` ga bisa kenapa ya om?

**Comment by alzearafat** [comment]
Iya harus di dalam virtualenv mas, biar gak ada masalah sama permission saat install depedensi nya.
Ini pake Python 3.6. Utk versi pillow nya coba cek di `requirements.txt`.

Kalau soal command migrate itu error karna ada depedensi yang belum/gagal di install. Kalau semua depedensi di requrements.txt nya berhasil di install, harusnya ga ada masalah :)

@januridp

**Comment by januridp** [comment]
udah bisa install `requirements.txt` om tinggal command yang migrate

**Comment by alzearafat** [comment]
coba : `pip install pytz` 

@januridp

**Comment by januridp** [comment]
munculnya:
Requirement already satisfied (use --upgrade to upgrade): pytz in /mnt/d/webroot/dev/python/django-id/lib/python2.7/site-packages
Cleaning up...

**Comment by januridp** [comment]
ini error kalo perintah `python manage.py runserver` dijalankan:
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/mnt/d/webroot/dev/python/django-id/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/mnt/d/webroot/dev/python/django-id/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/mnt/d/webroot/dev/python/django-id/local/lib/python2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/mnt/d/webroot/dev/python/django-id/local/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/mnt/d/webroot/dev/python/django-id/local/lib/python2.7/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named settings

**Comment by alzearafat** [comment]
Kayaknya path mismatch... Di Windows mungkin agak beda struktur nya. Coba bikin file ` __init__.py` kosong di setiap direktori nya.

Pakai Python 2.7 ya? Beda versi... Mungkin bisa error di app nya, karna sebagian kode nya kode Python 3.x :/

@januridp

**Comment by januridp** [comment]
bukannya file `__init__.py` emang udah ada di setiap folder ya om?
ane coba di ec2 aws juga sama om, untuk yg makemigrations itu tetep error pake python 3.5.2

**Comment by januridp** [comment]
`pip freeze`
certifi==2017.7.27.1
chardet==3.0.4
coverage==4.4.1
defusedxml==0.5.0
Django==1.11.5
django-allauth==0.33.0
django-autoslug==1.9.3
django-crispy-forms==1.6.1
django-markdownx==2.0.21
django-taggit==0.22.1
idna==2.6
Markdown==2.6.9
oauthlib==2.0.4
olefile==0.44
Pillow==4.3.0
pkg-resources==0.0.0
Pygments==2.2.0
python3-openid==3.1.0
pytz==2017.2
requests==2.18.4
requests-oauthlib==0.8.0
urllib3==1.22

**Comment by Keda87** [comment]
@januridp di dalem package `djangoid` apa ada file `settings.py`? soalnya di akhir error ada pesan `ImportError: No module named settings`

**Comment by januridp** [comment]
ada om `settings_test.py`

update:
makemigrations && migrate udah berhasil ga ada error, sudah bisa runserver.
Solusi: rename `settings_test.py` menjadi `settings.py`

**Comment by Keda87** [comment]
@januridp Iya bener, `settings_test.py` itu buat jalanin `./runtest.sh`.
`settings.py` memang gak di include di repo jadi bisa ambil template dari [wiki](https://github.com/django-id/website/wiki/Settings.py-Template) dan ditambahkan sendiri.
